<a href="https://colab.research.google.com/github/MuchammadAliRosyidi/DataMining/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
try:
    dataset = pd.read_csv('Data1.csv', delimiter=';')
    print("Dataset berhasil dibaca!")
except Exception as e:
    print(f"Terjadi kesalahan: {e}")

Dataset berhasil dibaca!


In [ ]:
print(dataset)

     Country   Age   Salary Purchased
0     France  44.0  72000.0        No
1  Indonesia  27.0  48000.0       Yes
2    Germany  30.0  54000.0        No
3      Spain  38.0  61000.0        No
4    Germany  40.0      NaN       Yes
5     France  40.0  58000.0       Yes
6      Spain   NaN  52000.0        No
7     France  48.0  79000.0       Yes
8  Indonesia  50.0  83000.0        No
9     France  37.0  67000.0       Yes


In [ ]:
print("Shape dari dataset:", dataset.shape)

# Lihat kolom-kolom yang terbaca
print("Kolom-kolom dataset:", dataset.columns)

# Sekarang coba pecah x dan y
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print("Fitur (x):", x)
print("Target (y):", y)

Shape dari dataset: (10, 4)
Kolom-kolom dataset: Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')
Fitur (x): [['France' 44.0 72000.0]
 ['Indonesia' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 40.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['France' 37.0 67000.0]]
Target (y): ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Indonesia' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 40.0 58000.0]
 ['Spain' 39.333333333333336 52000.0]
 ['France' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 0.0 40.0 58000.0]
 [0.0 0.0 0.0 1.0 39.333333333333336 52000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.0 39.333333333333336 52000.0]
 [0.0 1.0 0.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 27.0 48000.0]
 [1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 40.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
# Corrected import statement:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.7320508075688774 -0.22097527316805438 -1.0781259408412425]
 [0.0 1.0 0.0 -0.5773502691896258 -0.11995800543408718
  -0.07013167641635372]
 [1.0 0.0 0.0 -0.5773502691896258 0.4861456009697181 0.633562432710455]
 [0.0 0.0 0.0 1.7320508075688774 -0.4230098086359898 -0.30786617274297867]
 [0.0 0.0 1.0 -0.5773502691896258 -2.0897947262464545 -1.420463615551582]
 [1.0 0.0 0.0 -0.5773502691896258 1.0922492073735235 1.232653363453549]
 [0.0 0.0 1.0 -0.5773502691896258 1.395301010575426 1.5749910381638885]
 [1.0 0.0 0.0 -0.5773502691896258 -0.11995800543408718
  -0.5646194287757332]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -0.5773502691896258 -1.6352170214436004 -0.9069571034860727]
 [1.0 0.0 0.0 -0.5773502691896258 -0.5745357102369412 0.2056403393225306]]
